# Generated by Django 3.0.2 on 2021-05-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, max_length=999)),
                ('client_address', models.CharField(blank=True, max_length=999)),
                ('filler', models.CharField(blank=True, max_length=999)),
                ('filler_address', models.CharField(blank=True, max_length=999)),
                ('order', models.CharField(blank=True, max_length=999)),
                ('order_id', models.CharField(blank=True, max_length=999)),
                ('order_date', models.DateField(blank=True)),
                ('date', models.DateField(auto_now=True)),
                ('deadline', models.DateField(blank=True)),
                ('content', models.TextField(blank=True, verbose_name='asi, Al.%, Hind, Kogus, Reasumma')),
                ('total', models.FloatField(blank=True)),
            ],
        ),
    ]
