# Generated by Django 3.0.2 on 2021-05-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arved', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arve_template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arve', models.TextField(blank=True)),
            ],
        ),
    ]
