# Generated by Django 3.0.6 on 2020-05-07 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('navbar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=999)),
                ('EAN', models.CharField(blank=True, max_length=999)),
                ('manufacturer', models.CharField(blank=True, max_length=999)),
                ('in_stock', models.CharField(blank=True, max_length=999)),
                ('buy_price', models.FloatField(blank=True)),
                ('sell_price', models.FloatField(blank=True)),
                ('add_rate', models.FloatField(blank=True)),
                ('add_sum', models.FloatField(blank=True)),
                ('VAT_rate', models.FloatField(blank=True)),
                ('price_before_VAT', models.FloatField(blank=True)),
                ('image', models.FileField(upload_to='product_images')),
                ('image_url', models.CharField(blank=True, max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Product_lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=999)),
                ('description', models.TextField(blank=True)),
                ('categories', models.CharField(blank=True, max_length=9999)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navbar.Lang')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.Product')),
            ],
        ),
    ]
