# Generated by Django 3.0.6 on 2020-05-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='VAT_rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='add_rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='add_sum',
        ),
        migrations.RemoveField(
            model_name='product',
            name='buy_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_before_VAT',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sell_price',
        ),
        migrations.AddField(
            model_name='product',
            name='brand_image_url',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='items_in_package',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='measurements',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='more_images',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='special_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tracking_group',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='EAN',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product_lang',
            name='categories',
            field=models.CharField(max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='product_lang',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product_lang',
            name='name',
            field=models.CharField(max_length=999, null=True),
        ),
    ]
