# Generated by Django 3.0.6 on 2020-05-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0005_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bought',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
