# Generated by Django 3.0.6 on 2020-05-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0006_auto_20200514_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='front_page',
            field=models.BooleanField(default=False),
        ),
    ]
