# Generated by Django 3.0.6 on 2020-05-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0007_product_front_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='special_price_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='special_price_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
