# Generated by Django 3.0.6 on 2020-05-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0008_auto_20200525_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tracking_group_parent',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
