# Generated by Django 3.0.2 on 2021-03-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0010_browser_lang_item_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='browser_lang',
            name='sub_categories',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='item_lang',
            name='QTY',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='item_lang',
            name='add_to_cart',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='item_lang',
            name='in_stock',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
