# Generated by Django 3.0.2 on 2021-04-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0012_auto_20210402_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='special_price_end_date',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
