# Generated by Django 3.0.2 on 2021-04-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0014_auto_20210402_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='special_price_end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
