# Generated by Django 3.0.6 on 2020-05-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('email', models.CharField(blank=True, max_length=999, null=True)),
                ('first_name', models.CharField(blank=True, max_length=999, null=True)),
                ('last_name', models.CharField(blank=True, max_length=999, null=True)),
                ('cart', models.TextField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
