# Generated by Django 3.0.2 on 2021-03-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stripe_key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(blank=True, default='Test', max_length=999)),
                ('public_key', models.CharField(max_length=999)),
                ('private_key', models.CharField(max_length=999)),
            ],
        ),
    ]
