# Generated by Django 3.0.2 on 2021-03-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_stripe_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy_history',
            old_name='email',
            new_name='buyer_email',
        ),
        migrations.RenameField(
            model_name='buy_history',
            old_name='first_name',
            new_name='buyer_first_name',
        ),
        migrations.RenameField(
            model_name='buy_history',
            old_name='last_name',
            new_name='buyer_last_name',
        ),
        migrations.RemoveField(
            model_name='buy_history',
            name='cart',
        ),
        migrations.AddField(
            model_name='buy_history',
            name='shopping_cart',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='buy_history',
            name='shopping_cart_total',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
