# Generated by Django 3.0.2 on 2021-03-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210311_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_history',
            name='buyer_address',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
