# Generated by Django 3.0.2 on 2021-03-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20210311_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
