# Generated by Django 3.0.2 on 2021-03-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20210311_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_history',
            name='receipt',
            field=models.TextField(),
        ),
    ]
