# Generated by Django 3.0.2 on 2021-03-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_checkout_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout_lang',
            name='disclaimer',
            field=models.TextField(blank=True),
        ),
    ]
