# Generated by Django 3.0.6 on 2020-05-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=999, unique=True)),
                ('flag', models.FileField(upload_to='')),
            ],
        ),
    ]
