# Generated by Django 3.0.2 on 2021-03-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='contact',
            name='firm_name',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
