# Generated by Django 3.0.2 on 2021-04-16 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0004_auto_20210311_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar_lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(blank=True, max_length=999)),
                ('categories', models.CharField(blank=True, max_length=999)),
                ('browse', models.CharField(blank=True, max_length=999)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navbar.Lang')),
            ],
        ),
    ]
