# Generated by Django 3.0.2 on 2021-04-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0005_navbar_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar_lang',
            name='cart_is_empty',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='navbar_lang',
            name='checkout',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='navbar_lang',
            name='empty_cart',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
